# Generated by Django 3.1.4 on 2020-12-09 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20201208_2350'),
    ]

    operations = [
        migrations.AddField(
            model_name='wine',
            name='pairings',
            field=models.CharField(default=2, max_length=500),
            preserve_default=False,
        ),
    ]
