# Generated by Django 3.1.4 on 2020-12-09 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_gifts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Gifts',
            new_name='Gift',
        ),
    ]
