# Generated by Django 3.1.4 on 2020-12-10 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallery',
            name='year',
        ),
    ]
