# Generated by Django 3.1.4 on 2020-12-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_remove_gallery_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wine',
            name='rating',
        ),
    ]
