# Generated by Django 3.1.4 on 2020-12-15 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Checkout',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('address1', models.CharField(max_length=100)),
                ('address2', models.CharField(max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=500)),
                ('zip', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=500)),
                ('cardname', models.CharField(max_length=100)),
                ('cardnumber', models.CharField(max_length=100)),
                ('expiration', models.CharField(max_length=100)),
                ('cvv', models.CharField(max_length=500)),
            ],
        ),
    ]
